import type { Metadata } from "next";
import { Inknut_Antiqua, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});
const inknutAntiqua = Inknut_Antiqua({
    subsets: ["latin"],
    display: "swap",
    weight: "400",
    variable: "--font-inknut-antiqua",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${inter.variable} ${inknutAntiqua.variable}`}
        >
            <body className="font-body">{children}</body>
        </html>
    );
}
